### ISSUE TITLE
Http 403

### ISSUE THREAD

**Issue by researcher30** [zehengl/scrapy-indeed-company-reviews#33]
Hey Zehengl, 
thanks for creating the script. I tried to use it but similar to another scraper, I get a HTTP 403 error. I think they may have changed something on their site. Is it possible to adjust the code for that? 

Best

**Comment by zehengl** [comment]
Thanks for reporting. I will definitely take a look when I have a chance.

**Comment by researcher30** [comment]
Thank you, I part of fixed it by changing the "https" from the url to "http". That seems to solve the issue. 

I also added a new output on the position + former and current employee. Might be interesting to have as well.

**Comment by zehengl** [comment]
Thanks @researcher30. Do you mind sharing the fix and update in a PR?

**Comment by researcher30** [comment]
Sorry, I am not that familiar with PR. 

I have added this part which basically is the same you used for the date already. And then added it in the "items" file as well. 

            position = (
                BeautifulSoup(review.xpath('*//span[@itemprop="author"]').get())
                .get_text()
                .split(" - ")[0]
            )

            id = review.attrib["data-tn-entityid"]

            yield IndeedCompanyReviewsItem(
                id=id,
                rating=rating,
                text=text,
                pros=pros,
                cons=cons,
                date_created=date_created,
                position=position,
            )

**Comment by zehengl** [comment]
Thanks. I have added your changes to the main branch.
